version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://app_user:app_password@postgres:5432/uddoog
      - DIRECT_URL=postgresql://app_user:app_password@postgres:5432/uddoog
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      - STORAGE_TYPE=digitalocean
      - NODE_ENV=production
    networks:
      - app_network

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=uddoog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 